cc_binary(
  name = "audio_player",
  srcs = [
    "audio_player.cc",
  ],
  deps = [
    "//third_party/ffmpeg:avcodec",
    "//third_party/ffmpeg:avformat",
    "//third_party/ffmpeg:swresample",
  ],
)
