cc_binary(
  name = "audio_player",
  srcs = [
    "audio_player/audio_player.cc",
    "common.h",
  ],
  deps = [
    "//third_party/ffmpeg:avcodec",
    "//third_party/ffmpeg:avformat",
    "//third_party/ffmpeg:swresample",
  ],
)
